[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.5
    knolleary/PubSubClient @ ^2.8

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LITTLEFS

; .pio/ is local to each PC and must not be synchronized.
